# Configurações do MySQL
jdbcUrl=jdbc:mysql://localhost:3306/sakila?useSSL=false&serverTimezone=UTC
username=admin
password=Admin
driverClassName=com.mysql.cj.jdbc.Driver

# Otimizações para o Driver MySQL
dataSource.cachePrepStmts=true
dataSource.prepStmtCacheSize=250
dataSource.prepStmtCacheSqlLimit=2048
dataSource.useServerPrepStmts=true

# Configurações do Pool (HikariCP)
maximumPoolSize=10
minimumIdle=5
idleTimeout=600000
connectionTimeout=30000
poolName=MeuHikariPool
