spring.application.name=app

# =========================================
# CONFIGURAÇÃO DO BANCO DE DADOS
# =========================================

spring.datasource.url=jdbc:mariadb://localhost:3306/academia?useSSL=false&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=Admin
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# =========================================
# CONFIGURAÇÃO JPA / HIBERNATE
# =========================================

spring.jpa.hibernate.ddl-auto=update

# opções:
# create       -> recria o banco toda vez
# create-drop  -> cria ao iniciar e apaga ao finalizar
# update       -> atualiza tabelas automaticamente
# validate     -> valida estrutura
# none         -> desabilita

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# =========================================
# LOGS SQL (opcional)
# =========================================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
