spring.application.name=api
# ==================== H2 Database - Persistente ====================
spring.datasource.url=jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.type.preferred_enum_jdbc_type = VARCHAR
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (acesso via navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Opcional: Evitar erro de lock em alguns casos
spring.datasource.hikari.connection-timeout=30000